name: Test Automation WorkFlow

on:
schedule:
-cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework With Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
       name: screenshots
       path: screenshots/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
       name: Test Reports
       path: report.html

    - name: Upload Test Reports
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
         mkdir -p pu
    





    

  
